CREATE TABLE IF NOT EXISTS prog_langs (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    prog_lang VARCHAR(255) UNIQUE
);
CREATE TABLE IF NOT EXISTS speak_langs (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    speak_lang VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS skills (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    skill VARCHAR(255) UNIQUE
);
CREATE TABLE IF NOT EXISTS topics (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    topic VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS degrees (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    degree_name VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS experience_levels (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    experience_level VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS specializations (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    specialization VARCHAR(255) UNIQUE
);
