spring:
  datasource:
    url: jdbc:mysql://localhost:3306/perspective
    username: root
    password: 1Qazimodo237!
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations:
        - classpath:schema.sql
        - classpath:init.sql

server:
  port: 9091
  address: 0.0.0.0


security:
  jwt:
    secret: rdtfyghujikoml,
    access: 3600000
    refresh: 36000000
